# Generated by Django 3.1.7 on 2021-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PodID', models.PositiveIntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('Upload_Time', models.TimeField()),
                ('Host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongID', models.PositiveIntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('Upload_Time', models.TimeField()),
            ],
        ),
    ]
