# Generated by Django 3.1.7 on 2021-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioID', models.PositiveIntegerField(unique=True)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('Upload_Time', models.TimeField()),
            ],
        ),
    ]
