# Generated by Django 3.2.2 on 2021-05-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioserver', '0003_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
