# Generated by Django 3.2.2 on 2021-05-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioserver', '0005_auto_20210514_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='Host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='PodID',
            new_name='podId',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='Upload_Time',
            new_name='upload_time',
        ),
        migrations.AddField(
            model_name='podcast',
            name='participants',
            field=models.ManyToManyField(to='audioserver.Participant'),
        ),
    ]
