# Generated by Django 3.2.2 on 2021-05-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioserver', '0006_auto_20210516_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongID',
            new_name='songId',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Upload_Time',
            new_name='upload_time',
        ),
    ]
