# Generated by Django 3.2.2 on 2021-05-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioserver', '0007_auto_20210516_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='AudioID',
            new_name='audioId',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='Narrator',
            new_name='narrator',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='Upload_Time',
            new_name='upload_time',
        ),
    ]
