# Generated by Django 3.2.2 on 2021-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioserver', '0008_auto_20210516_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='audioserver.Participant'),
        ),
    ]
